baseurl: 
permalink: /:year/:month/:day/:title
auto: true
pygments: true
paginate: 20

safe: false

#Site config
title: Liu's Blog
keywords: Liu's Blog
description: Liu's Blog：http://blog.chit-chatting.tk/
url: http://blog.chit-chatting.tk/
feed: /atom.xml
favicon: /images/icon.ico

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 关于本站
    url: /about.html
  - text: 关于我
    url: /aboutme.html

#Author config
author:
    name: Liu
    email: liuxy6@gmail.com
    imageLink: http://ww4.sinaimg.cn/mw690/bf2cf099gw1e9rvkxijypj20a00a1my8.jpg
    simpleIntro: 我是 Liu ，一名普通的高中生。
    detailIntro:

#Follow me
follow:
  - class: fa fa-rss
    url: /atom.xml
  - class: fa fa-weibo
    url: http://t.qq.com
  - class: fa fa-github
    url: https://github.com/laurence6
  - class: fa fa-google-plus
    url: https://plus.google.com
  - class: fa fa-facebook
    url: https://www.facebook.com
  - class: fa fa-twitter
    url: https://twitter.com

#googleAnaly
googleAnaly:
  config: true
  id: UA-44812964-1
