gems: [jekyll-paginate]
baseurl:
permalink: /:year/:month/:day/:title
highlighter: rouge
paginate: 20
paginate_path: "/page:num"

safe: false

title: GoLaurence
keywords: ["GoLaurence", "computer"]
description: Blog of Laurence Liu, student of The Ohio State University
url: http://blog.laurence.tk
feed: /atom.xml
favicon: /images/icon.ico

nav:
  - text: <i class="fa fa-home fa-fw"></i>首页
    url: /index.html
  - text: <i class="fa fa-user fa-fw"></i>关于我
    url: /aboutme.html
  - text: <i class="fa fa-tags fa-fw"></i>标签
    url: /tags.html

author:
    name: Laurence
    email: liuxy6@gmail.com

follow:
  - class: fa fa-github fa-lg
    url: https://github.com/laurence6
  - class: fa fa-telegram fa-lg
    url: https://telegram.me/laurence6
  - class: fa fa-rss fa-lg
    url: /atom.xml

googleanalytics:
    enabled: false
    id: UA-44812964-1
share:
    enabled: false
