baseurl: 
permalink: /:year/:month/:day/:title
highlighter: pygments
paginate: 5
paginate_path: "/page:num"

safe: false

#Site config
title: Liu's Blog
keywords: Liu's Blog
description: Liu's Blog：http://blog.chit-chatting.tk/
url: http://blog.chit-chatting.tk/
feed: /atom.xml
favicon: /images/icon.ico

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类
    url: /categories.html
  - text: 标签
    url: /tags.html
  - text: 关于本站
    url: /about.html
  - text: 关于我
    url: /aboutme.html
  - text: 友情链接
    url: /links.html
  - text: '<i class="fa fa-rss"></i>RSS'
    url: /atom.xml

#Author config
author:
    name: Liu
    email: liuxy6@gmail.com
    imageLink: http://ww3.sinaimg.cn/mw690/bf2cf099gw1ebigbjo6x1j20go0gomz0.jpg
    simpleIntro: 我是 Liu ，一名普通的高中生。
    detailIntro:

#Follow me
follow:
  - class: fa fa-rss fa-lg
    url: /atom.xml
  - class: fa fa-weibo fa-lg
    url: http://t.qq.com
  - class: fa fa-github fa-lg
    url: https://github.com/laurence6
  - class: fa fa-google-plus fa-lg
    url: https://plus.google.com
  - class: fa fa-facebook fa-lg
    url: https://www.facebook.com
  - class: fa fa-twitter fa-lg
    url: https://twitter.com

customlinks:
  - item:
    message: Friends

#googleAnaly
googleAnaly:
  config: true
  id: UA-44812964-1
